export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_PASSWORD_RESET_REQUEST = "USER_PASSWORD_RESET_REQUEST";
export const USER_PASSWORD_RESET_SUCCESS = "USER_PASSWORD_RESET_SUCCESS";
export const USER_PASSWORD_RESET_FAIL = "USER_PASSWORD_RESET_FAIL"

export const USER_EMAIL_TO_RESET_PASSWORD_REQUEST =
  "USER_EMAIL_TO_RESET_PASSWORD_REQUEST";
export const USER_EMAIL_TO_RESET_PASSWORD_SUCCESS = "USER_EMAIL_TO_RESET_PASSWORD_SUCCESS"
export const USER_EMAIL_TO_RESET_PASSWORD_FAIL = "USER_EMAIL_TO_RESET_PASSWORD_FAIL"